### ISSUE TITLE
Cookies not set

### ISSUE THREAD

**Issue by diegozuber** [oauthjs/angular-oauth2#103]
I use the module in an Ionic project. All works perfect exept that the cookies were not set. What could be the problem?

**Comment by diegozuber** [comment]
For testing purpose I replaced in the Provider File (oauth-token-provider.js) by the setToken the cookie.putObject() to a console.log(data). 

![bereichsaufnahme 2](https://cloud.githubusercontent.com/assets/21689209/18185548/8d803e08-709e-11e6-92b8-7f8c471075f8.png)

If I am right I should see the server response in the console when I login, but nothing. But I can see in the Developer Tools that the request was successful and the server gives the right data back, as expected.

Hope you can help me out somehow.

**Comment by ruipenso** [comment]
I've no experience with Ionic, but AFAIK cookies will not work and you'll need to use localStorage.

We're close to support other storage methods - Refs #97.

**Comment by diegozuber** [comment]
Okay problem is solved now. I replaced the cookie storage method with HTML5 localstorage and all works fine now. Seems Ionic doesn't support cookies.
