### ISSUE TITLE
Change configuration to authenticate on another server

### ISSUE THREAD

**Issue by Damore** [oauthjs/angular-oauth2#106]
On my config.js I added the OAuthProvider and I've configured it as it should be:

`
    OAuthProvider.configure({
        baseUrl: "mybaseUrl.com.br",
        clientId: 123,
        clientSecret: 1785452,
        grantPath: '/oauth/token'
    });`
However, this is valid only for the first authentication. After that, I have to authenticate on another server with another baseUrl, clientId and clientSecret. 

What should I do to change the configuration of OAuthProvider?

**Comment by joaogranado** [comment]
Hi @Damore sorry for the late response but I have been busy. This issue will be fixed with #87 with a new release today.

**Comment by ruipenso** [comment]
This is closed with the latest release 4.1.0.
