### ISSUE TITLE
Issue with queryString.stringify(data) 

### ISSUE THREAD

**Issue by vcmcinc** [oauthjs/angular-oauth2#108]
I am getting the following error when calling Oauth.getAccessToken (data) 

Type error:  Cannot read property 'stringify' of undefined.  

Please note that I downloaded and included the dependency re query-string in my index.html

**Comment by gordinh** [comment]
i am getting the same error

**Comment by gordinh** [comment]
@vcmcinc my problem was because i didn't put the `query_string` on the gulpfile. After that, it works.

**Comment by elmus** [comment]
hi! i had the same error, is there some solution for that ?? 
Thanks !

**Comment by ruipenso** [comment]
What @gordinh said.

**Comment by jamendub** [comment]
Sorry to bother you but I am running into that exact same issue.
Problem is that I don't get how you "put the query_string" on the gulpfile ???
@gordinh could you share a code snippet with us please ?

**Comment by jamendub** [comment]
Ok after few trials I got what you meant : I had to include the query-string js file before the angular-oauth2 js file !!!! Hope this helps the next guy ;)

**Comment by alextech1** [comment]
I found out my issue was that I was using import instead of const so I change this:
`import {queryString} from 'query-string';`
to this:
`const queryString = require('query-string');`

**Comment by IamGiel** [comment]
In my case, I did this mistake -> `import { qs } from "qs;`   The issue is 'named export' versus 'default export'.  In the qs library, Im guessing it is a default export so the answer is to remove the curly braces from the import statement.

`import qs from "qs"; `
