### ISSUE TITLE
Warning: Tried to load angular more than once.

### ISSUE THREAD

**Issue by jaimemateo** [oauthjs/angular-oauth2#123]
I first thought this Warning was not related to angular-oauth2 package but when I got rid of it in my project, then the Warning was gone. 

Is there anyone having this Warning as well? I have angular-oauth2 defined as **devDependency** in package.json and then I'm importing it with `require('angular-oauth2)`. I'm using **Webpack** as well, and I followed some Issues recalling this issue like [this one](https://github.com/webpack/webpack/issues/2134) but didn't really find a solution.

Thanks in advance.

**Comment by erhardos** [comment]
Same here. I analyzed bundle with webpack-bundle-analyzer and it's look like angular-oauth2 contains another node_modules with own angular.
