### ISSUE TITLE
'npm install' is broken

### ISSUE THREAD

**Issue by darkurse** [oauthjs/angular-oauth2#126]
Hi,

I cloned and tried to 'npm install' the project but it does not work.

```
npm verb cwd C:\Work\Others\github\angular-oauth2
npm verb Windows_NT 10.0.16299
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
npm verb node v6.10.3
npm verb npm  v5.6.0
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/Nikku/node-browserify.git
npm ERR!
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
npm verb exit [ 1, true ]
```

### **update**
I'm not familiar with browserify so I'm gonna take two blind guesses here :
 - `github.com/Nikku/node-browserify` package doesnt exist and might got renamed to **karma-browserify**.
 - Or it seems like `node-browserify` was actually from repo `https://github.com/substack/node-browserify/` which got itself renamed to  `https://github.com/browserify/browserify` ( See [browserify changelog](https://github.com/browserify/browserify/blob/ccc02139481fb7f107009c2bd60a5e6f03610a63/changelog.markdown) for this change between version 14.4.0 and 14.5.0 )

I looked at the source on how to change this but I have honestly no clue how to fix this. Any hints ?

ps: Issue #121 mentions it but I wanted to create a proper issue entry for this

**Comment by darkurse** [comment]
I think I found the reason and logged the issue on browserify repository [browserify/issues/1786](https://github.com/browserify/browserify/issues/1786)

**Comment by nikku** [comment]
This is not related to browserify but https://github.com/nikku/karma-browserify/issues/213.

I highly encourage users of `karma-browserify<=4` to upgrade to the replacement `karma-browserif@5`:

```
npm i --save-dev karma-browserify@latest watchify browserify
```
