### ISSUE TITLE
 use guide

### ISSUE THREAD

**Issue by prostoVladislav** [oauthjs/angular-oauth2#81]
We have created a config . what's next?
Tell please. that needs to be done in the controller.

**Comment by anand9** [comment]
even i am wondering what to do next

**Comment by fandong117** [comment]
@prostoVladislav 
` OAuth.getAccessToken(user, options); ` return a response promise and you can execute a callback.

eg: 
```
var promise  = OAuth.getAccessToken(user);
promise.then(function (result) {
    $rootScope.access_token = result.data.access_token;
})
```

**Comment by jmwilkinson** [comment]
The really confusing thing is why you need a username and password to retrieve user data... isn't the whole point of oauth moving the necessity to get a username and password to the auth provider?

The documentation should contain an [SSCCE](http://sscce.org/)... which it doesn't right now.

**Comment by ruipenso** [comment]
Basically, after configuration you can use the `getAccessToken` method on your controller. By sending the `username` and `password`, it will store the `access_token` which will be used in the next request as an `Authorization`.

@jmwilkinson There are different ways to [obtain authorization](https://tools.ietf.org/html/rfc6749#section-4).

It would be great to have a better documentation and an example, but honestly I don't have time at the moment.

Duplicated by #67.
