### ISSUE TITLE
Interceptor don't work

### ISSUE THREAD

**Issue by mpozzo** [oauthjs/angular-oauth2#83]
I add this library in my project 

works fine but if a do a $http.get or $http.post  my header don't contain any baerer token

can we help me?

Thanks 

This is my request header :+1: 
Accept  
application/json, text/plain, _/_
Accept-Encoding 
gzip, deflate
Accept-Language 
it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
Connection  
keep-alive
Host  
pagandoangular.local:8080
Referer 
http://pagandoangular.local:8080/
User-Agent  
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

My config :
.config(['OAuthProvider', function(OAuthProvider){
      OAuthProvider.configure({
          baseUrl: 'http://cliente2.pagando.local:8080',
          clientId: 'testclient',
          grantPath: '/oauth',
          revokePath: '/oauth',
          clientSecret: 'testpass' // optional
        });
    }]);

**Comment by ruipenso** [comment]
Did you successfully retrieved a token after a `getAccessToken` call? Check if this is related to #21.

**Comment by ruipenso** [comment]
Closing this.
