### ISSUE TITLE
update oauth serverUrl after application start

### ISSUE THREAD

**Issue by lionelB** [oauthjs/angular-oauth2#84]
Hello,
I plan to use your module, but after reading the doc, it seems that the only way to make it work is to configure it using a `.config()` block. 
Unfortunatly, the app I work on can connect retrieve the oauth servers info at runtine, after application started.
Is there something I can achieve using your lib ?
Thanks.

**Comment by lionelB** [comment]
I'm considering making a PR to remove the mandatory `.config()` part... is it something you would consider to merge or not ?

**Comment by ruipenso** [comment]
Hi @lionelB,

I think the `config` is convenient for most of the cases. What I think we can do if to pass an extra `config` parameter to each method that overrides the `url`.

WDYT?

**Comment by lionelB** [comment]
Hi @ruipenso 
sorry for the late response, I think its a clever compromise, since it doesn't break existing code and mimic known api like $http.
would you like I made a PR for that ?

**Comment by pgom** [comment]
@lionelB, feel free to create a PR for this.

**Comment by lionelB** [comment]
done =)

**Comment by lionelB** [comment]
@ruipenso  @pgom would love to have some feedback on my PR.
