### ISSUE TITLE
Moving to oauth organization

### ISSUE THREAD

**Issue by ruipenso** [oauthjs/angular-oauth2#85]
As part of a community effort to group oauth-related packages developed in js together, a new organization ([oauthjs](https://github.com/oauthjs)) has been created to host the most popular packages.

The idea behind this proposal is to increase package awareness and build even more community around them. The popular [node-oauth-server](https://github.com/thomseddon/node-oauth2-server/issues/162) will make the switch soon, as well as the koa wrapper [koa-oauth-server](https://github.com/thomseddon/koa-oauth-server).

In the next hours we will be moving this package to its new home too!

**Comment by ruimarinho** [comment]
Project has been moved! @ruipenso, @pgom and @pgom will be leading this project on the new organization.

Links and repository information should be updated to reflect the package's new home :)
