### ISSUE TITLE
getRefreshToken returns "d"

### ISSUE THREAD

**Issue by JordanSDev** [oauthjs/angular-oauth2#88]
I tried to use the plugin, but when I try      console.dir(OAuth.getRefreshToken());
it returns "d"
![screenshot at 2016-05-09 10 07 02](https://cloud.githubusercontent.com/assets/18655774/15107066/cdbfe13e-15cd-11e6-8e35-3acbacf999ae.png)

**Comment by ruipenso** [comment]
@JordanSDev Are you trying to debug the minified version?

**Comment by JordanSDev** [comment]
No, I'm just trying to get the token, but it returns me d or undefined

**Comment by ruipenso** [comment]
`OAuth.getRefreshToken()` returns a promise. So, you should be logging the promise resolve, i.e.,

```
OAuth.getRefreshToken().then((response) => {
  console.log(response);
})
```

**Comment by JordanSDev** [comment]
Ok, but then, how can I extract access_token ?
![screenshot at 2016-05-09 14 17 24](https://cloud.githubusercontent.com/assets/18655774/15112799/d221c4fe-15f0-11e6-89c6-e02ea7afec42.png)

**Comment by JordanSDev** [comment]
OAuth.getRefreshToken().then((response) => {
  var tk=(response.data.access_token);
  console.dir(tk);
})

**Comment by JordanSDev** [comment]
OAuth.getRefreshToken().then((response) => {
  var tk=(response.data.access_token);
  console.dir(tk);
})

Returns an object, how to get a String ?

**Comment by ruipenso** [comment]
`var token = response.data.access_token`?

**Comment by JordanSDev** [comment]
Yes, it returns me the string token, no prob. But, when I try

$http({
      method: 'GET', 
      

      headers: headers,


      url: 'http://api.example.com/api/v1/public/getInfosById/1?token='+**token**+''})
    .success(function(data){
    console.log("success");
    console.log(data);
 

    })

It cannot access my 'token', returns Object or nothing

**Comment by ruipenso** [comment]
When you call `getRefreshToken()`, the token will be stored as a cookie using the `OAuthToken` service. You can always get the `token` using the same service.

But, why do want to send the token as a query parameter? The token must be sent as an `Authorization` header, which is already done by the `angular-oauth2` module. You can read more about it [here](https://tools.ietf.org/html/rfc6750).

Closing this issue since your problem is no longer related with `angular-oauth2`.

**Comment by JordanSDev** [comment]
I just want to access the token outside the promise

**Comment by ruipenso** [comment]
`OAuthToken.getToken()`
